// Code generated by dixian-platform/scripts/contracts/contract.mjs. DO NOT EDIT.

package dixiancontract

const ContractSHA256 = "5ce5178d4996e9fb9969e7a39d6155abaedbe50aa040204db333bd57a019ba69"

var RequestContextFields = []string{
	"request_id",
	"trace_id",
	"log_number",
	"tenant_id",
	"user_id",
	"identity_source",
	"effective_role_assignment_ids",
	"scope",
	"department_id",
	"module_id",
	"project_id",
	"conversation_id",
	"run_id",
	"run_context_id",
	"device",
	"ip_address",
}

var RequestContextRequiredFields = []string{
	"request_id",
	"trace_id",
	"log_number",
	"tenant_id",
	"user_id",
	"identity_source",
	"effective_role_assignment_ids",
	"scope",
	"device",
	"ip_address",
}

var SSEEventTypes = []string{
	"started",
	"delta",
	"artifact",
	"citation",
	"tool_pending",
	"approval_pending",
	"completed",
	"failed",
	"cancelled",
}

var SSETerminalEventTypes = []string{
	"completed",
	"failed",
	"cancelled",
}

type UUID string
type TraceID string
type LogNumber string
type IdentitySource string
type ScopeKind string
type DeviceChannel string
type ErrorCode string
type SSEEventType string

const (
	ErrorCodeRequestInvalid        ErrorCode = "REQUEST_INVALID"
	ErrorCodeAuthUnauthenticated   ErrorCode = "AUTH_UNAUTHENTICATED"
	ErrorCodeAuthForbidden         ErrorCode = "AUTH_FORBIDDEN"
	ErrorCodeResourceNotFound      ErrorCode = "RESOURCE_NOT_FOUND"
	ErrorCodeResourceConflict      ErrorCode = "RESOURCE_CONFLICT"
	ErrorCodeIdempotencyKeyReused  ErrorCode = "IDEMPOTENCY_KEY_REUSED"
	ErrorCodeVersionConflict       ErrorCode = "VERSION_CONFLICT"
	ErrorCodeEventResumeExpired    ErrorCode = "EVENT_RESUME_EXPIRED"
	ErrorCodeRateLimited           ErrorCode = "RATE_LIMITED"
	ErrorCodeDependencyBadGateway  ErrorCode = "DEPENDENCY_BAD_GATEWAY"
	ErrorCodeDependencyUnavailable ErrorCode = "DEPENDENCY_UNAVAILABLE"
	ErrorCodeDependencyTimeout     ErrorCode = "DEPENDENCY_TIMEOUT"
)

const (
	SSEEventStarted         SSEEventType = "started"
	SSEEventDelta           SSEEventType = "delta"
	SSEEventArtifact        SSEEventType = "artifact"
	SSEEventCitation        SSEEventType = "citation"
	SSEEventToolPending     SSEEventType = "tool_pending"
	SSEEventApprovalPending SSEEventType = "approval_pending"
	SSEEventCompleted       SSEEventType = "completed"
	SSEEventFailed          SSEEventType = "failed"
	SSEEventCancelled       SSEEventType = "cancelled"
)

var ErrorHTTPStatus = map[string]int{
	string(ErrorCodeRequestInvalid):        400,
	string(ErrorCodeAuthUnauthenticated):   401,
	string(ErrorCodeAuthForbidden):         403,
	string(ErrorCodeResourceNotFound):      404,
	string(ErrorCodeResourceConflict):      409,
	string(ErrorCodeIdempotencyKeyReused):  409,
	string(ErrorCodeVersionConflict):       409,
	string(ErrorCodeEventResumeExpired):    409,
	string(ErrorCodeRateLimited):           429,
	string(ErrorCodeDependencyBadGateway):  502,
	string(ErrorCodeDependencyUnavailable): 503,
	string(ErrorCodeDependencyTimeout):     504,
}

type ScopeRef struct {
	Kind       ScopeKind `json:"kind"`
	ResourceID UUID      `json:"resource_id"`
	Actions    []string  `json:"actions"`
}

type DeviceContext struct {
	Channel   DeviceChannel `json:"channel"`
	DeviceID  string        `json:"device_id,omitempty"`
	UserAgent string        `json:"user_agent,omitempty"`
}

type RequestContext struct {
	RequestID                  UUID           `json:"request_id"`
	TraceID                    TraceID        `json:"trace_id"`
	LogNumber                  LogNumber      `json:"log_number"`
	TenantID                   UUID           `json:"tenant_id"`
	UserID                     UUID           `json:"user_id"`
	IdentitySource             IdentitySource `json:"identity_source"`
	EffectiveRoleAssignmentIDs []UUID         `json:"effective_role_assignment_ids"`
	Scope                      []ScopeRef     `json:"scope"`
	DepartmentID               *UUID          `json:"department_id,omitempty"`
	ModuleID                   *UUID          `json:"module_id,omitempty"`
	ProjectID                  *UUID          `json:"project_id,omitempty"`
	ConversationID             *UUID          `json:"conversation_id,omitempty"`
	RunID                      *UUID          `json:"run_id,omitempty"`
	RunContextID               *UUID          `json:"run_context_id,omitempty"`
	Device                     DeviceContext  `json:"device"`
	IPAddress                  string         `json:"ip_address"`
}

type ErrorEnvelope struct {
	ErrorCode         ErrorCode `json:"error_code"`
	Message           string    `json:"message"`
	RequestID         UUID      `json:"request_id"`
	TraceID           TraceID   `json:"trace_id"`
	LogNumber         LogNumber `json:"log_number"`
	Retryable         bool      `json:"retryable"`
	RetryAfterSeconds *int      `json:"retry_after_seconds,omitempty"`
}

type CursorPage[T any] struct {
	Items      []T     `json:"items"`
	NextCursor *string `json:"next_cursor"`
	HasMore    bool    `json:"has_more"`
	Total      int     `json:"total"`
}

type SSERunEvent struct {
	SchemaVersion  int            `json:"schema_version"`
	EventID        UUID           `json:"event_id"`
	RequestID      UUID           `json:"request_id"`
	TraceID        TraceID        `json:"trace_id"`
	LogNumber      LogNumber      `json:"log_number"`
	ConversationID UUID           `json:"conversation_id"`
	RunID          UUID           `json:"run_id"`
	Sequence       int            `json:"sequence"`
	Type           SSEEventType   `json:"type"`
	OccurredAt     string         `json:"occurred_at"`
	Payload        map[string]any `json:"payload"`
}

var ErrorEnvelopeFields = []string{
	"error_code",
	"message",
	"request_id",
	"trace_id",
	"log_number",
	"retryable",
	"retry_after_seconds",
}

var CursorPageFields = []string{
	"items",
	"next_cursor",
	"has_more",
	"total",
}

var SSERunEventFields = []string{
	"schema_version",
	"event_id",
	"request_id",
	"trace_id",
	"log_number",
	"conversation_id",
	"run_id",
	"sequence",
	"type",
	"occurred_at",
	"payload",
}

var IdentitySources = []string{
	"wecom",
	"oidc",
	"local",
}

var ScopeKinds = []string{
	"company",
	"department",
	"module",
	"agent",
	"project",
	"self",
}

var DeviceChannels = []string{
	"web",
	"wecom",
	"api",
	"service",
}

const (
	IdentitySourceWecom IdentitySource = "wecom"
	IdentitySourceOidc  IdentitySource = "oidc"
	IdentitySourceLocal IdentitySource = "local"
)

const (
	ScopeKindCompany    ScopeKind = "company"
	ScopeKindDepartment ScopeKind = "department"
	ScopeKindModule     ScopeKind = "module"
	ScopeKindAgent      ScopeKind = "agent"
	ScopeKindProject    ScopeKind = "project"
	ScopeKindSelf       ScopeKind = "self"
)

const (
	DeviceChannelWeb     DeviceChannel = "web"
	DeviceChannelWecom   DeviceChannel = "wecom"
	DeviceChannelApi     DeviceChannel = "api"
	DeviceChannelService DeviceChannel = "service"
)
